"""initial_gem_sentinel_schema

Revision ID: e9c80d2f845b
Revises: 
Create Date: 2026-09-16 10:58:04.974299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c80d2f845b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('gst_score', sa.Integer(), nullable=True),
    sa.Column('pan_score', sa.Integer(), nullable=True),
    sa.Column('udyam_score', sa.Integer(), nullable=True),
    sa.Column('doc_completeness_score', sa.Integer(), nullable=True),
    sa.Column('financial_score', sa.Integer(), nullable=True),
    sa.Column('consistency_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_compliance_scores_id'), 'compliance_scores', ['id'], unique=False)
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('document_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_document_hash'), ['document_hash'], unique=False)
        batch_op.create_foreign_key('fk_documents_uploaded_by_users', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_uploaded_by_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_document_hash'))
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('document_hash')
        batch_op.drop_column('storage_path')

    op.drop_index(op.f('ix_compliance_scores_id'), table_name='compliance_scores')
    op.drop_table('compliance_scores')

    # ### end Alembic commands ###
